function mifigura(X1,Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 24-Sep-2019 08:55:39

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create plot
plot(X1,Y1);

% Create ylabel
ylabel('F(\omega)');

% Create xlabel
xlabel('\omega');

% Create title
title('Gráfica de la señal F(\omega) vs \omega');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'XAxisLocation','origin','YAxisLocation','origin');
end